[package]
name = "roots_common"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
rustc-hash = "2.0.0"
web-time = "1.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
send_wrapper = "0.6.0"
